import type { Metadata } from "next";
import { Work_Sans } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "./globals.css";
import Header from "./components/header/Header";
import { ThemeProvider } from "./components/providers/theme-provider";

const workSans = Work_Sans({
  variable: "--font-work-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Cloud Hosting",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <body className={`${workSans.variable} `}>
          <ToastContainer theme="colored" position="top-center" />
          <Header />
          <main className="w-[21rem]  md:w-[40rem] lg:w-[64rem] m-auto">
            {children}
          </main>
        </body>
      </ThemeProvider>
    </html>
  );
}
